services:
    python-server:
      container_name: python-server
      image: python-server:1.0
      build:
        dockerfile: Dockerfile
      restart: always
      volumes:
        - ./app:/home/jonnattan/app
        - ../envs/file.aws_credentials:/home/jonnattan/.aws/credentials  # Archivo que no puede ser versionado
      ports:
        - "8085:8085"
        - "5000:5000"
      env_file:
        - ../envs/file.env
      networks:
        - db-net
networks:
  db-net:
