services:
    python-server:
      container_name: python-server
      image: jonnattangc/pyserver:1.0.0
      build:
        dockerfile: Dockerfile
      restart: always
      volumes:
        - ./app:/home/jonnattan/app
      ports:
        - "8085:8085"
      env_file:
        - ../envs/file.env
      networks:
        - db-net
      #command: tail -f /home/jonnattan/app/extensions.py 
networks:
  db-net:
