version: '3.9'
services:
    python-server-test:
      container_name: python-server-test
      image: 3.14-rc-slim⁠
      volumes:
        - ./app:/home/jonnattan/app
      ports:
        - "8086:8086"
      env_file:
      - .env
      networks:
        - db-net
networks:
  db-net:
