version: '3.9'
services:
    python-server-test:
      container_name: python-server-test
      image: test:v3.11.8
      volumes:
        - ./requirements.txt:/home/jonnattan/requirements.txt
        - ./app:/home/jonnattan/app
        - ./.aws_credentials:/home/jonnattan/.aws/credentials
      ports:
        - "8086:8086"
      env_file:
      - .env
      networks:
        - db-net
networks:
  db-net:
