version: "3.9"
services:
    python-server:
      container_name: python-server
      # Crea la imagen con el archivo Dockerfile de esta misma carpeta
      image: python-server:v1.7
      restart: always
      volumes:
        - ./app:/home/jonnattan/app
        - ../file.aws_credentials:/home/jonnattan/.aws/credentials  # Archivo que no puede ser versionado
      ports:
        - "8085:8085"
      env_file:
        - ../file.env
      networks:
        - db-net
networks:
  db-net:
