name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: jonna-server

    steps:
    - uses: actions/checkout@v3
    - name: Construir imagen
      run: docker build -t prueba:$(date +%s) .
